# Generated by Django 4.1.dev20220418143310 on 2022-04-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('progresoPorcentual', models.IntegerField(null=True)),
                ('minutosJugados', models.IntegerField(null=True)),
                ('usuario', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
